### ISSUE TITLE
How to best integrate Flask-SocketIO

### ISSUE THREAD

**Issue by aninternetof** [JackStouffer/Flask-Foundation#14]
Can you give any recommendation for the best way to integrate [Flask-SocketIO](http://flask-socketio.readthedocs.io/en/latest/) into the Flask-Foundation structure?

In manage.py, I added `socketio = SocketIO(app)`, then I created a new Flask-Script command to run `socketio.run(app)` instead of the built-in debug server.

However, now I'm unsure how to import/access `socketio` from another file so that I can use `@socketio.on('message')` and `socketio.start_background_task()`. Is there a better place than manage.py for me to create `socketio = SocketIO(app)`?

**Comment by JackStouffer** [comment]
Extension initializations go in extensions.py

Just like flask login, you then init the extension with the app inside the app creation function.

socketio is then imported from extensions.py in the controller files

**Comment by aninternetof** [comment]
Many thanks!
