### ISSUE TITLE
Expired Cert

### ISSUE THREAD

**Issue by SamProtas** [JackStouffer/Flask-Foundation#16]
This may be the wrong forum for this report, but the docs this repo links to force-redirect to HTTPS with an expired Lets Encrypt cert. Chrome gives very scary warnings about your website.

**Comment by SamProtas** [comment]
https://jackstouffer.com/flask-foundation/

**Comment by JackStouffer** [comment]
Thanks for letting me know, I'll get on this as soon as possible

**Comment by JackStouffer** [comment]
Fixed
