### ISSUE TITLE
modernizr missing

### ISSUE THREAD

**Issue by zerox1212** [JackStouffer/Flask-Foundation#17]
Thanks for a great template.

modernizr lib isn't actually included in your repo but the pages reference it. From what I understand you have to go to the modernizr website and build it for the features you need to check for. Is there a reason it's referenced but nothing is in `static/js/vendor` ?

**Comment by JackStouffer** [comment]
Thanks for bring this to my attention.

Yeah, I used to include it when they offered a standardized download and I removed it when they stopped. I'll remove the reference in the docs.

**Comment by JackStouffer** [comment]
https://github.com/JackStouffer/Flask-Foundation/pull/18
