### ISSUE TITLE
Production server

### ISSUE THREAD

**Issue by bsamadi** [JackStouffer/Flask-Foundation#19]
I have used Flask-Foundation. I would like to create a production server. I searched for a tutorial but I found tutorials for simple Flask apps that don't use the Flask-Script extension. Do you know of any tutorial that I can follow?

**Comment by JackStouffer** [comment]
Well, there's my book: https://www.amazon.com/dp/B00YSILB26/ref=cm_sw_r_cp_awdb_YALHzb321PJWE

Otherwise, look up "nginx uWSGI".
