### ISSUE TITLE
SCSS Missing?

### ISSUE THREAD

**Issue by PylotLight** [JackStouffer/Flask-Foundation#20]
So I'm trying to load some example templates using foundation docs for my Python flask app and noticed that it wasn't looking the same. 
Then found that it looks like I'm missing any SCSS in the installed module which from my understanding is what foundation is built on. 
One example is that callouts just render with the text with no border or other styling as exampled in the docs.
Am I meant to import this another way, or is there something else I'm missing with this one?

I can provide more info or pictures if needed.
Thanks.

**Comment by lochyw** [comment]
Oh, this extension is massively out of date.
I downloaded new files and sorted some stuff  out.
But this extension still needs updating I think.
